Feature/multi assets
input-output-hk/cardano-explorer-app pull request #380
Opened 2021-01-20 16:02 UTC by jplorek-atix

This PR adds support for multiassets on the transaction and address pages
    
the assets are displayed on the following fields: 

- address balance tokens, 
- transaction minted tokens 
- transaction burned tokens 
- transaction outputs address 
- transaction input address

each field has:

- -asset name
- -quantity 
- -policy id

For this implementation the multi assets branch on the cardano graphql was used
https://github.com/input-output-hk/cardano-graphql/tree/feature/multi-asset

2021-01-22 05:54 UTC, cleverca22 commented
is `packages-cache/bignumber.js-9.0.1.tgz` supposed to be included in the git repo? i would expect it to be downloaded automatically

2021-01-22 14:20 UTC, lgobbi-atix commented
> is `packages-cache/bignumber.js-9.0.1.tgz` supposed to be included in the git repo? i would expect it to be downloaded automatically

I think so, maybe @rhyslbw can clarify?

2021-02-02 05:26 UTC, rhyslbw commented
> is packages-cache/bignumber.js-9.0.1.tgz supposed to be included in the git repo?

Yes, we use yarn offline package cache to facilitate reproducible builds.

2021-02-02 07:06 UTC, rhyslbw commented on source/features/address/ui/AddressSummary.tsx
> +                  {/* TODO: add DE and JA translation*/}
TODO: add DE and JA translation

2021-02-02 07:07 UTC, rhyslbw commented on source/features/address/ui/AddressSummary.tsx
> +                  {/* TODO: add DE and JA translation*/}
TODO: add DE and JA translation

2021-02-02 07:07 UTC, rhyslbw commented on source/features/transactions/components/TransactionInfo.tsx
> +              {/* TODO: add DE and JA translation*/}
TODO: add DE and JA translation

2021-02-02 07:07 UTC, rhyslbw commented on source/features/transactions/components/TransactionInfo.tsx
> +              {/* TODO: add DE and JA translation*/}
TODO: add DE and JA translation

2021-02-02 07:11 UTC, rhyslbw requested changes
Great work. We just need DE and JA translations for the following phrases:

- Ada Balance
- Tokens balance
- Policy ID
- This address has no tokens
- Minted tokens
- Burned tokens

I'll sort this out.

2021-02-02 10:04 UTC, eddyjlhaigh commented
Here are the Japanese translations:

Ada Balance ADA残高
Tokens balance トークン残高
Policy ID ポリシーID
This address has no tokens このアドレスにはトークンがありません
Minted tokens 鋳造済みトークン
Burned tokens バーン済みトークン

2021-02-03 15:50 UTC, eddyjlhaigh requested changes
Looks good accept for one minor issue. The "Tokens balance" is not horizontally aligned with an addresses tokens, as seen here https://explorer.mary-qa.dev.cardano.org/en/address.html?address=addr_test1qz3gkzmatgtvw7zdkttvchftja4fys79krn7rue6x7dc43t939ww4vt849h8wpjv38czxt4q97vc8438tte28amvwm3qm63e2w. I played with the element and found changing the `margin-top` from `5px` to `0px` on the `TransactionTokenList_token` fixed this.

2021-02-03 15:54 UTC, DominikGuzei commented
Hey @rhyslbw I have pushed the DE translations … not sure if it's relevant but I saw this error when running `yarn dev`:
![grafik](https://user-images.githubusercontent.com/172414/106772556-6d24cb00-6640-11eb-962c-9535e9508ada.png)

2021-02-03 15:58 UTC, DominikGuzei commented
hm … really strange, my GIT client says everything is up-to-date (pushed) but here on Github my commit with the German translations does not seem to appear 🤔

2021-02-04 04:31 UTC, rhyslbw commented
Thanks @DominikGuzei 
Ah sorry I should have warned you about the dev backend needed to be rebuilt. The error is just reflecting it's not in sync yet

2021-02-26 10:33 UTC, merged